### PR TITLE
Move Jenkins configuration from Gitea

### PR DESCRIPTION
**Pull request by Retropikzel**

### CODE REVIEW

**Comment by lassik** [comment]
Thanks a lot for getting around to doing this. LGTM.

**Comment by Retropikzel** [comment]
The conflicting files:

- jenkins/docker-compose.yml
- jenkins/update.sh 

should be replaced by the versions from my fork.

But I'm not quite sure how to do that?

**Comment by lassik** [comment]
I did:

```
git remote add Retropikzel git@github.com:Retropikzel/server-configuration.git
git fetch --all
git checkout Retropikzel/jenkins jenkins/docker-compose.yml
git checkout Retropikzel/jenkins jenkins/update.sh
```

Those commands made no changes to the files in PR #2, so I merged PR #2 into master.

Please check that master is OK. I'll add you to this GitHub organization so you can push commits directly to master.

**Comment by Retropikzel** [comment]
> I did:
> 
> ```
> git remote add Retropikzel git@github.com:Retropikzel/server-configuration.git
> git fetch --all
> git checkout Retropikzel/jenkins jenkins/docker-compose.yml
> git checkout Retropikzel/jenkins jenkins/update.sh
> ```
> 
> Those commands made no changes to the files in PR #2, so I merged PR #2 into master.
> 
> Please check that master is OK. I'll add you to this GitHub organization so you can push commits directly to master.

Master is okay. Thanks!

**Pull request closed without merging**
